---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: test
data:
  db_name: drone
  user: drone
  # delete root_pass and user_pass once mysql-secret is working properly
  root_pass: password
  user_pass: password
