---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: test
  labels:
    app: mysql
spec:
  ports:
  - name: sql
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP
